org.gradle.caching=true
group=io.ballerina.lib
version=1.0.0-SNAPSHOT

checkstylePluginVersion=10.12.0
spotbugsPluginVersion=6.0.18
shadowJarPluginVersion=8.1.1
downloadPluginVersion=5.4.0
releasePluginVersion=2.8.0
ballerinaGradlePluginVersion=2.3.1

ballerinaLangVersion=2201.12.0

debeziumVersion=3.0.8.Final

rocketmqVersion=5.1.4
rocketmqProtoVersion=2.0.3
rocketmqLoggingVersion=1.0.1
rocketmqRocksdbVersion=1.0.3

commonsLang3Version=3.18.0
commonsCliVersion=1.5.0
commonsValidatorVersion=1.7
commonsDigesterVersion=2.1
concurrentlinkedhashmap=1.4.2

zstdJniVersion=1.5.2-2
lz4Version=1.8.0

grpcVersion=1.75.0
protobufVersion=3.25.8
tomcatAnnotationsVersion=6.0.53
guavaVersion=32.0.1-jre
failureaccessVersion=1.0.1
perfmarkVersion=0.27.0
fastjsonVersion=1.2.83

otelVersion=1.32.0
otelAlphaVersion=1.32.0-alpha
otelSemconvVersion=1.29.0-alpha

okhttpVersion=4.11.0
okioVersion=3.2.0
kotlinVersion=1.6.20
